export enum EventType {
  FRIENDSHIP_REQUEST = "FRIENDSHIP_REQUEST",
  FRIENDSHIP_ACCEPTED = "FRIENDSHIP_ACCEPTED",
  USER_JOIN_ROOM = "USER_JOIN_ROOM",
  MESSAGE_SENT = "MESSAGE_SENT",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  FRIEND_LOGGED_IN = "FRIEND_LOGGED_IN",
}
